# Generated by Django 3.2.3 on 2023-05-28 17:40

import data.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_data', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to=data.models.Datasource.upload_path_doc, validators=[data.models.Datasource.file_size])),
                ('insert_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
