# Generated by Django 3.2.3 on 2023-06-01 21:25

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20230601_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='descripteur_global',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
