# Generated by Django 3.2.3 on 2023-06-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_datasource_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='codes_pages_de_garde',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='liens_descripteurs_locaux_type',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='nombre_mot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='nombre_paragraphe',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='nombre_phrase',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='titres_pages_de_garde',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
