# Generated by Django 3.2.3 on 2023-06-01 22:18

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_datasource_descripteur_global'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='nombre_mot',
            new_name='conclusion_nombre_mot',
        ),
        migrations.RenameField(
            model_name='datasource',
            old_name='nombre_paragraphe',
            new_name='conclusion_nombre_paragraphe',
        ),
        migrations.RenameField(
            model_name='datasource',
            old_name='nombre_phrase',
            new_name='conclusion_nombre_phrase',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='liens_descripteurs_locaux_type',
        ),
        migrations.AddField(
            model_name='datasource',
            name='descripteur_conclusion',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='descripteur_introduction',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='introduction_nombre_mot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='introduction_nombre_paragraphe',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='introduction_nombre_phrase',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='pg_titre_nombre_mot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='pg_titre_nombre_paragraphe',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='pg_titre_nombre_phrase',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
