# Generated by Django 3.2.3 on 2023-05-28 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_student', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('domain', models.CharField(choices=[('', 'Please select'), ('Agriculture', 'Agriculture'), ('Engineering', 'Engineering'), ('Health Professions', 'Health Professions'), ('Math and Computer Science', 'Math and Computer Science'), ('Physical and Life Sciences', 'Physical and Life Sciences'), ('Social Sciences', 'Social Sciences'), ('Humanities', 'Humanities'), ('Business and Management', 'Business and Management'), ('Education', 'Education'), ('Fine and Applied Arts', 'Fine and Applied Arts'), ('Legal Studies and Law Enforcement', 'Legal Studies and Law Enforcement'), ('Communications and Journalism', 'Communications and Journalism')], default='', max_length=200)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(blank=True, choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Banned ', 'Banned '), ('Closed', 'Closed'), ('Canceled', 'Canceled')], default='Inactive', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('insert_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
