# Generated by Django 3.2.3 on 2023-05-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='about',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
