# Generated by Django 3.2.3 on 2023-05-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20230528_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='region',
        ),
    ]
